name: Build and deploy personal qwik website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependecies
        run: npm install
        working-directory: ./qwik-app

      - name: Build app
        run: npm run predeploy
        working-directory: ./qwik-app

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./qwik-app/dist # The folder the action should deploy.
