name: Build and deploy personal qwik website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependecies
        run: npm install
        working-directory: ./qwik-app

      - name: build and deploy site
        run: npm run deploy
        working-directory: ./qwik-app
